---
name: "ci"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.12.0

      - name: Install dev-dependencies
        run: yarn

      - name: Run CI
        run: yarn ci
